version: '3.2'

services:
  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - 3000:3000
    environment:
      ALLOWED_HOSTS: '127.0.0.1 localhost 181.41.194.182 sre.demoo.lol'
      DEBUG: 'True'
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DJANGO_DB: postgresql
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
    volumes:
      - static_volume:/app/staticfiles

  celery:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: /app/celery-entrypoint.sh
    environment:
      ALLOWED_HOSTS: '127.0.0.1 localhost 181.41.194.182 sre.demoo.lol'
      DEBUG: 'True'
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DJANGO_DB: postgresql
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
    depends_on:
      - django
      - redis
    volumes:
      - static_volume:/app/staticfiles
  redis:
    restart: unless-stopped
    image: redis:alpine 
    expose:
      - 6379
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    
volumes:
  postgres_data: {}
  static_volume: {}